options:
  logging: CLOUD_LOGGING_ONLY   # <-- ปิด requirement logs bucket

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_URI}', '.']

images:
  - '${_IMAGE_URI}'