# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY   # ตัด requirement เรื่อง logs bucket

steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=asia-southeast1-docker.pkg.dev/$PROJECT_ID/etl-repo/student-info-etl:$SHORT_SHA
      - --dockerfile=./Dockerfile
      - --context=.
      - --cache=true
      - --verbosity=debug

images:
  - asia-southeast1-docker.pkg.dev/$PROJECT_ID/etl-repo/student-info-etl:$SHORT_SHA